"use strict";
var batman = "Batman";
var linternaVerde = 'Linterna Verde';
var volcanNegro = "Volc\u00E1n Negro";
console.log(batman);
console.log(linternaVerde);
console.log(volcanNegro);
var concatenar = "Los héroes: " + batman + ", " + linternaVerde + ", " + volcanNegro;
console.log(concatenar);
var concat = "Los h\u00E9roes con formato diferente son: " + batman + ", " + linternaVerde + ", " + volcanNegro;
console.log(concat);
